### ISSUE TITLE
No circular progress bar in MS Edge

### ISSUE THREAD

**Issue by I-NOZex** [GMartigny/circular-progress-bar#1]
Microsoft Edge 42.17134.1.0
Microsoft Windows 10 Pro
Version 10.0.17134 Build 17134

**Comment by GMartigny** [comment]
Sorry this issue slip under my radar 🙇 
Sadly `circular-progress-bar` rely on CSS conic-gradient and I'm not going to polyfill unsupported browser.
The good news is that it's an official W3C component and should be supported by all major browser in the near future. You can still check [which browser currently support it](https://caniuse.com/#feat=css-conic-gradients).
